### ISSUE TITLE
onceover run diff causes errors

### ISSUE THREAD

**Issue by tuxmea** [dylanratcliffe/onceover-octocatalog-diff#11]
OS: MacOS 12
using rvm and ruby 2.5.8
Same on the puppet-dev-tools container and CentOS

Relevant part seems to be: 

cannot load such file -- onceover/controlrepo (LoadError) (OctocatalogDiff::Errors::BootstrapError)

```
Exit: 1
Status: failed
Errors:
/usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog-util/bootstrap.rb:150:in `run_bootstrap': bootstrap failed for /tmp/ocd-ipc-20220503-2955-1lgql3p/ocd-bootstrap-checkout-20220503-2967-yz4hox: /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- onceover/controlrepo (LoadError) (OctocatalogDiff::Errors::BootstrapError)
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /tmp/ocd-ipc-20220503-2955-1lgql3p/ocd-bootstrap-checkout-20220503-2967-yz4hox/tmp/infrastructure__puppet__r10k_on_puppet.training20220427.betadots.training20220503-1-16frlh8/bootstrap_script.rb:3:in `<main>'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog-util/bootstrap.rb:96:in `bootstrap_directory'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog/computed.rb:96:in `bootstrap'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog/computed.rb:113:in `build_catalog'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog.rb:96:in `build'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:241:in `build_catalog'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:34:in `call'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:34:in `execute'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:197:in `execute_task'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:119:in `block (2 levels) in run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:117:in `fork'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:117:in `block in run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `each'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `each_with_index'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:94:in `run_tasks'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:92:in `build_catalog_parallelizer'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:29:in `catalogs'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/api/v1/catalog-diff.rb:34:in `catalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/cli.rb:151:in `run_octocatalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/cli.rb:125:in `cli'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/bin/octocatalog-diff:34:in `<top (required)>'
	from /usr/local/bundle/bin/octocatalog-diff:23:in `load'
	from /usr/local/bundle/bin/octocatalog-diff:23:in `<main>'
```

**Comment by tuxmea** [comment]
Same on the puppet-dev-tools container:

```
Exit: 1
Status: failed
Errors:
/usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog-util/bootstrap.rb:150:in `run_bootstrap': bootstrap failed for /tmp/ocd-ipc-20220503-2955-1lgql3p/ocd-bootstrap-checkout-20220503-2967-yz4hox: /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- onceover/controlrepo (LoadError) (OctocatalogDiff::Errors::BootstrapError)
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /tmp/ocd-ipc-20220503-2955-1lgql3p/ocd-bootstrap-checkout-20220503-2967-yz4hox/tmp/infrastructure__puppet__r10k_on_puppet.training20220427.betadots.training20220503-1-16frlh8/bootstrap_script.rb:3:in `<main>'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog-util/bootstrap.rb:96:in `bootstrap_directory'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog/computed.rb:96:in `bootstrap'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog/computed.rb:113:in `build_catalog'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/catalog.rb:96:in `build'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:241:in `build_catalog'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:34:in `call'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:34:in `execute'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:197:in `execute_task'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:119:in `block (2 levels) in run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:117:in `fork'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:117:in `block in run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `each'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `each_with_index'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:114:in `run_tasks_parallel'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/parallel.rb:94:in `run_tasks'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:92:in `build_catalog_parallelizer'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/util/catalogs.rb:29:in `catalogs'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/api/v1/catalog-diff.rb:34:in `catalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/cli.rb:151:in `run_octocatalog_diff'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/lib/octocatalog-diff/cli.rb:125:in `cli'
	from /usr/local/bundle/gems/octocatalog-diff-1.6.0/bin/octocatalog-diff:34:in `<top (required)>'
	from /usr/local/bundle/bin/octocatalog-diff:23:in `load'
	from /usr/local/bundle/bin/octocatalog-diff:23:in `<main>'
```
